### ISSUE TITLE
not work with two m17 

### ISSUE THREAD

**Issue by Sandteufel** [Anonym-tsk/homeassistant-starline#1]
error in log
---
```
Error setting up entry Application 248 for starline
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 190, in async_setup
    hass, self
  File "/config/custom_components/starline/__init__.py", line 26, in async_setup_entry
    await account.update()
  File "/config/custom_components/starline/account.py", line 77, in update
    await self._hass.async_add_job(self._async_update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/starline/account.py", line 68, in _async_update
    self._api.update()
  File "/usr/local/lib/python3.7/site-packages/starline/starline_api.py", line 42, in update
    self._devices[device_id].update(device_data)
  File "/usr/local/lib/python3.7/site-packages/starline/device.py", line 42, in update
    self._ctemp = device_data["ctemp"]
KeyError: 'ctemp'
```

**Comment by Sandteufel** [comment]
As I understand module not support starline m15 m17.

**Comment by Anonym-tsk** [comment]
So, let's investigate this problem.
Please enable debug logging for component in Home Assistant
```yaml
logger:
  logs:
    custom_components.starline: debug
    starline: debug
```
Then try to add integration with Home Assistant UI and provide logs here.

**Comment by Sandteufel** [comment]
Вроде вот эта часть дебага Вам нужна
`019-11-08 22:32:30 DEBUG (SyncWorker_0) [starline.base_api] StarlineApi GET request: https://developer.starline.ru/json/v2/user/109050/user_info
2019-11-08 22:32:30 DEBUG (SyncWorker_0) [starline.base_api]   Payload: None
2019-11-08 22:32:30 DEBUG (SyncWorker_0) [starline.base_api]   Data: None
2019-11-08 22:32:30 DEBUG (SyncWorker_0) [starline.base_api]   JSON: None
2019-11-08 22:32:30 DEBUG (SyncWorker_0) [starline.base_api]   Headers: {'Cookie': 'slnet=5AD1B326AB039702DB16E4EAD621D017'}
2019-11-08 22:32:30 DEBUG (SyncWorker_0) [starline.base_api]   Response: <Response [200]>
2019-11-08 22:32:30 DEBUG (SyncWorker_0) [starline.base_api]   Data: {'devices': [{'alias': 'Шарлотта', 'device_id': 351513054663890, 'imei': '351513054663890', 'battery': 0.0, 'gps_lvl': 11, 'mon_type': 2, 'phone': '+798ХХХХХХХХ', 'status': 1, 'ts_activity': 1573154241, 'type': 1, 'typename': 'Маяк', 'interval': 10, 'mayak_temp': 9, 'position': {'x': 5Х.03, 'y': 3Х.8, 'ts': 1573241539, 'sat_qty': 11, 'r': 0}, 'balance': {'active': {'value': 9, 'currency': '', 'operator': '', 'state': 'low_balance'}}, 'car_alr_state': {}, 'car_state': {}, 'functions': ['events', 'gsm', 'info', 'position', 'push', 'state', 'tracking'], 'controls': []}, {'alias': 'Сайрус', 'device_id': 353173065473116, 'imei': '353173065473116', 'battery': 0.0, 'gps_lvl': 6, 'mon_type': 2, 'phone': '+7YYYYYYYYYY', 'status': 2, 'ts_activity': 1573231459, 'type': 1, 'typename': 'Маяк', 'interval': 10, 'mayak_temp': 36, 'position': {'x': 5TTTTT, 'y': 3PPPPPP1, 'ts': 1573223574, 's': 11, 'dir': 2, 'sat_qty': 6, 'r': 0}, 'balance': {'active': {'value': 36, 'currency': '', 'operator': '', 'state': 'low_balance'}}, 'car_alr_state': {}, 'car_state': {}, 'functions': ['events', 'gsm', 'info', 'position', 'push', 'state', 'tracking'], 'controls': []}], 'shared_devices': [], 'code': 200, 'codestring': 'OK'}
2019-11-08 22:32:30 INFO (MainThread) [homeassistant.setup] Setting up notify
2019-11-08 22:32:30 INFO (MainThread) [homeassistant.setup] Setup of domain notify took 0.0 seconds.
2019-11-08 22:32:30 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=notify>
2019-11-08 22:32:30 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event platform_discovered[L]: service=load_platform.camera, platform=netatmo, discovered=>
2019-11-08 22:32:30 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event platform_discovered[L]: service=load_platform.notify, platform=mobile_app, discovered=>
2019-11-08 22:32:30 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Application 248 for starline
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 190, in async_setup
    hass, self
  File "/config/custom_components/starline/__init__.py", line 26, in async_setup_entry
    await account.update()
  File "/config/custom_components/starline/account.py", line 77, in update
    await self._hass.async_add_job(self._update_data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/starline/account.py", line 68, in _update_data
    self._api.update()
  File "/usr/local/lib/python3.7/site-packages/starline/starline_api.py", line 46, in update
    self._devices[device_id].update(device_data)
  File "/usr/local/lib/python3.7/site-packages/starline/device.py", line 42, in update
    self._ctemp = device_data["ctemp"]
KeyError: 'ctemp'`

**Comment by Sandteufel** [comment]
суть в том, что у маяка вы выдаче запроса существенно меньше параметров, и как я понял ваш скрипт утыкается именно в это.

**Comment by Anonym-tsk** [comment]
@Sandteufel обновите через HACS и проверьте. Должно заработать.

**Comment by Sandteufel** [comment]
Все работает, благодарю!
